/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcgs_srx_Util_JniUtil */

#ifndef _Included_com_mcgs_srx_Util_JniUtil
#define _Included_com_mcgs_srx_Util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    getUsbMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_getUsbMode
  (JNIEnv *, jobject);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    setUsbMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mcgs_srx_Util_JniUtil_setUsbMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    setBeeTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_setBeeTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    getLcdStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_getLcdStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    setLcdStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_setLcdStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    getBacklightbrightness
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_getBacklightbrightness
  (JNIEnv *, jobject);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    setBacklightbrightness
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_setBacklightbrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    getRtcStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_getRtcStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    getRtcTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_getRtcTime
  (JNIEnv *, jobject);

/*
 * Class:     com_mcgs_srx_Util_JniUtil
 * Method:    setRtcTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mcgs_srx_Util_JniUtil_setRtcTime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
